version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: app_db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    # depends_on:
    #   mongo:
    #     condition: service_healthy
    environment:
      MONGO_URI: mongodb://mongo:27017/app_db
    ports:
      - "5000:5000"
    # volumes:
    #   - ./backend:/app

  frontend:
    build: ./frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    # volumes:
    #   - ./frontend:/app

volumes:
  mongo_data:
